---
- hosts: all

  # ignore_errors: yes

  vars:
    docker_users:
      - ec2-user

  become: yes

  pre_tasks:
    - name: Update packages
      raw: bash -c "[[ -f /usr/bin/yum ]] && yum update || apt-get -qqy update"
      register: output
      changed_when: output.stdout != "\r\n"

    - name: Install python for Ansible
      raw: bash -c "[[ -f /usr/bin/yum ]] && yum install python || apt-get -qqy install python-minimal"
      register: output
      changed_when: output.stdout != "\r\n"

    - name: Gathering Facts
      setup:
  
  roles:
    # Play role common with base packages
    - role: common

    # Play role docker-rhel to install docker and docker-compose
    - role: docker-rhel
      when: "ansible_os_family == 'RedHat'"

    # Play role geerlingguy.java to install java
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
