# roles/common/tasks/debian.yml
- name: Ensure git is present
  apt:
    name: git
    state: present

- name: Ensure vim is present
  apt:
    name: vim
    state: present

- name: Ensure mc is present
  apt:
    name: mc
    state: present
