---
- name: Enable RHEL extras repository
  rhsm_repository:
    name: rhui-REGION-rhel-server-extras

- name: Enable RHEL optional repository
  rhsm_repository:
    name: rhui-REGION-rhel-server-optional
