---
- name: Configure optional repo
  ini_file:
    dest: '/etc/yum.repos.d/redhat-rhui.repo'
    section: 'rhui-REGION-rhel-server-optional'
    option: enabled
    value: 1

- name: Configure extras repo
  ini_file:
    dest: '/etc/yum.repos.d/redhat-rhui.repo'
    section: 'rhui-REGION-rhel-server-extras'
    option: enabled
    value: 1
